- name: Configure and Set Up Local Environment
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    workspace: "{{ lookup('env', 'HOME') }}/workspace"

  tasks:
    - name: Update APT on Debian systems
      apt:
        name: "*"
        state: latest
      tags:
        - install
        - core
      when: ansible_distribution == "Debian"

    - name: Include SSH tasks
      include_tasks: tasks/ssh.yml

    - name: Include Git setup tasks
      include_tasks: tasks/git-setup.yml

    - name: Include Core setup tasks
      include_tasks: tasks/core-setup.yml

    - name: Include Node.js setup tasks
      include_tasks: tasks/node-setup.yml

    - name: Include NPM packages setup tasks
      include_tasks: tasks/npm-packages.yml

    - name: Include Zsh setup tasks
      include_tasks: tasks/zsh-setup.yml

    - name: Include Projects setup tasks
      include_tasks: tasks/projects.yml

    - name: Include Neovim setup tasks
      include_tasks: tasks/nvim-setup.yml

    - name: Include Dotfiles setup tasks
      include_tasks: tasks/dotfiles.yml

    - name: Include Productivity tools setup tasks
      include_tasks: tasks/productivity-tools.yml

    - name: Install Mac Apps
      include_tasks: tasks/mac-apps.yml

