- name: Setup lua-language-server lua lsp
  ansible.builtin.git:
    repo: "git@github.com:LuaLS/lua-language-server.git"
    recursive: yes
    dest: "{{ workspace }}/lua-language-server"
  become: true
  become_user: kodizen
  tags:
    - install
    - lsp

- name: Print workspace variable
  debug:
    msg: "Workspace directory is {{ workspace }}"
  tags:
    - install
    - lsp
- name: Set correct permissions for lua-language-server directory
  file:
    path: "{{ workspace }}/lua-language-server"
    owner: kodizen
    group: kodizen
    recurse: yes
    mode: "u+rwX,g+rX,o+rX"
  become: true
  become_user: kodizen
  tags:
    - install
    - lsp

- name: build the damn lua-language-server deez lsp
  become: true
  ansible.builtin.shell:
    cmd: ./make.sh
    chdir: "{{ workspace }}/lua-language-server"
  tags:
    - install
    - lsp
