- name: Check if Node.js is already installed
  shell: "command -v node && command -v npm"
  register: node_check
  changed_when: false
  ignore_errors: yes

- name: Install n globally
  become: false
  shell: curl -L https://bit.ly/n-install | bash -s -- -y
  when: node_check.rc != 0

  tags:
    - install
    - node

- name: Check installation of n and environment
  become: false
  shell: |
    echo "n location: $(which n)"
    echo "PATH: $PATH"
  register: debug_output
  ignore_errors: true

- name: Print debug information
  debug:
    msg: "{{ debug_output.stdout_lines }}"

- name: Source bashrc and install Node using n
  become: true
  shell: |
    {{ lookup('env', 'HOME') }}/n/bin/n 18
  tags:
    - install
    - node

