- name: Install n globally
  become: false
  shell: curl -L https://bit.ly/n-install | bash -s -- -y
  tags:
    - install
    - node

- name: Check installation of n and environment
  become: false
  shell: |
    echo "n location: $(which n)"
    echo "PATH: $PATH"
  register: debug_output
  ignore_errors: true

- name: Print debug information
  debug:
    msg: "{{ debug_output.stdout_lines }}"

- name: Source bashrc and install Node using n
  become: true
  shell: |
    /home/kodizen/n/bin/n 18
  tags:
    - install
    - node
