- name: Debug SSH key path
  debug:
    msg: "{{ playbook_dir }}/.ssh/id_rsa"

- name: Ensure .ssh directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh private key
  copy:
    src: "./.ssh/id_rsa"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh public key
  copy:
    src: "./.ssh/id_rsa.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', './.ssh/id_rsa.pub') }}"
  tags:
    - dotfiles
    - install
    - ssh

